### ISSUE TITLE
config: auto install API endpoints

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-datamodel#18]
Something like: 

```python
# ext.py
def init_config(self, app):
    for k in dir(config):
        if k.startswith('<CFGPREFIX>_'):
            app.config[k] = getattr(config, k)
        elif k == 'RECORDS_REST_ENDPOINTS' \
                    and app.config.get('<CFGPREFIX>_ENDPOINTS_ENABLED', True):
                app.config['RECORDS_REST_ENDPOINTS'].update(getattr(config, k))
```

```python 
# config.py
<CFGPREFIX>_ENDPOINTS_ENABLED

RECORDS_REST_ENDPOINTS = {
    .... # note: name changed (no prefix)
}
```

Probably the same should happen with Records-UI

This way 1) by default we add the data models endpoints to the configuration and 2) a user can switch them off if they like to change something.

**Comment by slint** [comment]
I'm not sure if this would work correctly, depending on the loading order of the extensions. E.g. if the following happens in the application factory in `invenio-base`:

1. Config loaded (instance's `config.py`, `invenio.cfg`, environment, etc)
2. Extensions loaded:
    a. `InvenioRecordsREST` loaded first, registering endpoints from `RECORDS_REST_ENDPOINTS`
    b. `<ExtensionClass>` loaded second, modifies `RECORDS_REST_ENDPOINTS`, but these will not be used again...
3. ...
4. App loaded but without the REST endpoints from `<Extension>`

For this to work with `invenio-records-rest` (and `records-UI`) I see three solutions:

1. Remove the dynamic blueprint registration that takes place in [InvenioRecordsREST.init_app](https://github.com/inveniosoftware/invenio-records-rest/blob/7c32876db1af213e81cbcaa7227eccb64f3c83b2/invenio_records_rest/ext.py#L90-L92) and make it an `invenio_base.blueprints` entrypoint... This would also require allowing the entrypoint to point to a callable, so that [`invenio_records_rest.views.create_blueprint`](https://github.com/inveniosoftware/invenio-records-rest/blob/7c32876db1af213e81cbcaa7227eccb64f3c83b2/invenio_records_rest/views.py#L116), can be passed as the entrypoint.
2. Using the [`app_loaded` signal ](https://github.com/inveniosoftware/invenio-base/blob/e70c8316cfabac5b2fafada03b93d00b3f7af094/invenio_base/app.py#L118) in `InvenioRecordsREST`
3. We'll have to load the `<Extension>.init_config` in the [`config_loader` part](https://github.com/inveniosoftware/invenio-base/blob/e70c8316cfabac5b2fafada03b93d00b3f7af094/invenio_base/app.py#L94-L95) of `invenio-base`. This is bit non-intuitive though and requires a lot of changes in many places...

**Comment by lnielsen** [comment]
I think It will work as long as you set ``RECORDS_REST_ENDPOINTS = {}`` in the ``mysite.config`` module. This way, Records-REST will never set ``RECORDS_REST_ENDPOINTS`` and loading will be predictable (given that no data model module overwrites each others URL prefix).

**Comment by slint** [comment]
What I'm concerned with is not config overwriting issues for `RECORDS_REST_ENDPOINTS`, but the fact that loading order of the extensions will affect what endpoints will be created. E.g in the extension loading part (let's assume all extensions have REST endpoints defined in their configuration):

1. `ExtA`
1. `ExtB`
1. `InvenioRecordsREST` (current config includes `ExtA` + `ExtB` endpoints which are passed to [`create_blueprints`](https://github.com/inveniosoftware/invenio-records-rest/blob/7c32876db1af213e81cbcaa7227eccb64f3c83b2/invenio_records_rest/ext.py#L90-L92)
1. `ExtC`
1. `ExtD`

The final result is that the configuration for the endpoints of `ExtC` and `ExtD` was never passed to the `invenio_records_rest.views.create_blueprint` function.
